function qSet_new = interpolation(QSet,n)
%   Augment an existing QSet by adding interpolated configurations 
%   -> QSet is a n x q matrix, n is the number of parameter, q is the number of
%       frames. Each column is a configuration
%   -> n <int> the number of configration to add between two existing configurations
%
%   CÔTE Geoffrey - CORROENNE Timothée

    qSet_new = [];

    % Iterate overall existing configuration points
    for j=1:size(qSet,1)-1
        % Extract both configuration where we will append interpolated configurations in between
        q1 = qSet(j,:);
        q2 = qSet(j+1,:);
        l_q = [q1];

        % Iterate over the new points generated by a lineair interpolator.
        for i=1:n
            signt1 = sign(q1(3)-q2(3));
            qi = q1+((i+1)/(n+2))*(q2-q1);
            if(abs(q1(3)-q2(3))>abs(q1(3)-q2(3)-signt1*2*pi))
                qi(3) = q1(3)+((i+1)/(n+2))*(q2(3)-q1(3)+signt1*2*pi);
            end
            l_q=[l_q;qi];
        end
        
        qSet_new=[qSet_new;l_q];
    end
end